export const REINITIALIZED_STATE = 'REINITIALIZED_STATE';
export const FETCH_ALL_USER_SUCCESSFULLY = 'FETCH_ALL_USER_SUCCESSFULLY';
export const LOGGED_IN = 'LOGGED_IN';
export const GET_ALL_QUESTIONS = 'GET_ALL_QUESTIONS';
export const GET_QUESTION_BY_ID = 'GET_QUESTION_BY_ID';
export const SUBMIT_QUESTION_ANSWER_SUCCESSFULLY = 'SUBMIT_QUESTION_ANSWER_SUCCESSFULLY';
